### ISSUE TITLE
Why rendered image has less color than in-game image?

### ISSUE THREAD

**Issue by daominah** [UNOWEN-OwO/md_spine_tools#2]
I feel like Blender rendered image has less color than in-game image, and can I fix the color, example:

Blender render Accesscode:
![accesscode_talker_15032](https://github.com/UNOWEN-OwO/md_spine_tools/assets/10495757/9597e69a-926c-4276-a126-8129470d3bd6)
In game Accesscode:
![accesscode_talker_full](https://github.com/UNOWEN-OwO/md_spine_tools/assets/10495757/25e20154-fb59-44d3-b444-9a59a43fe145)

Blender render  El Shaddoll Construct:
![el_shaddoll_construct_11258](https://github.com/UNOWEN-OwO/md_spine_tools/assets/10495757/3aff2545-fc75-4b0f-8c6e-bf139b40dd70)
In game El Shaddoll Construct:
![el_shaddoll_construct_transparent](https://github.com/UNOWEN-OwO/md_spine_tools/assets/10495757/86996d8a-2423-4a85-817c-547d555b0379)

**Comment by netazero** [comment]
I had the same problem.
And how did you got in-game image?Through Spine?

**Comment by daominah** [comment]
"in-game image" I mean static card art from Master Duel game files that I extracted with github.com/Perfare/AssetStudio

**Comment by kumopult** [comment]
blender的默认颜色模式并不是sRGB，普通的png纹理导入后都会显得比较灰。你可以在Render Properties最下方的Color Management一栏中把View Transform从Filmic改为Standard，这样就能恢复颜色了

**Comment by daominah** [comment]
thank @kumopult , it worked
